#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

function place_app_in_desktop() {
  local app_name="$1"
  local desktop_id="$2"

  if [[ -z "$app_name" || -z "$desktop_id" ]]; then
    echo "Usage: place_app_in_desktop APP_NAME DESKTOP_ID"
    return 1
  fi

  yabai -m rule --add app="^${app_name}$" space="${desktop_id}"

  for id in $(yabai -m query --windows | jq ".[] | select(.app == \"${app_name}\") | .id"); do
    yabai -m window "$id" --space "$desktop_id"
  done
}

place_app_in_desktop "Firefox" 9
place_app_in_desktop "Fleet" 3
place_app_in_desktop "CLion" 3
place_app_in_desktop "PyCharm" 3
place_app_in_desktop "iTerm2" 2
place_app_in_desktop "Obsidian" 8
place_app_in_desktop "Todoist" 8
place_app_in_desktop "Steam" 4

echo "yabai configuration loaded $(date).."
